### ISSUE TITLE
Place holder for cartesian product

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdblib#16]
Need to add a function to lcdblib to do the cartesian product. For example, given a sample table:

| sample | tissue |
|--------|--------|
| one    | ovary  |
| two    | testis |

and some set of values `{'num': [100, 200]}` build:

| sample | tissue | num |
|--------|--------|-----|
| one    | ovary  | 100 |
| one    | ovary  | 200 |
| two    | testis | 100 |
| two    | testis | 200 |

The following works for two dataframes, but would be nice to generalize df2 to be either a dataframe, list, or dict.

```python
from itertools import product

def cartesian(df1, df2):
    rows = product(df1.iterrows(), df2.iterrows())
    df = pd.DataFrame(left.append(right) for (_, left), (_, right) in rows)
    return df.reset_index(drop=True)
```

**Comment by daler** [comment]
https://docs.python.org/3/library/itertools.html#itertools.product useful for this, and possibly http://toolz.readthedocs.io/en/latest/api.html

**Comment by jfear** [comment]
haha forgot to add the imports, I am actually using itertools.product

**Comment by daler** [comment]
Sorry, I should have recognized that -- still caffeinating!

**Comment by jfear** [comment]
me too!!

**Comment by jfear** [comment]
Added PR #18 to address this. Simple function that dates a dataframe and a (dict | series | dataframe) and calculates the cartesian product.
